version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ips-data-acquisition-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: ips-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ips_data_acquisition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

